/**
 * UberLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/05/2016
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "http://mocksvc.mulesoft.com/mocks/2f2cd6a7-402c-43e3-a454-5479b02dcfab{0}.uber.com/{1}",

    //TODO: Replace the ApiMode with an appropriate value
    apiMode : "TODO: Replace",

    //TODO: Replace the Version with an appropriate value
    version : "TODO: Replace",

    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the OAuthAccessToken with an appropriate value
    oAuthAccessToken : "TODO: Replace"

};

module.exports = configuration;

